module.exports = {
  href: '/api/v2/root_hospital_lab_results',
  meta: {
    href: '/api/v2/root_hospital_lab_results',
    hrefCollection: '/api/v2/root_hospital_lab_results',
    name: 'root_hospital_lab_results',
    label: 'Lab results',
    description: 'lab results are hospital specific, so placed in the hospital package',
    attributes: [
      {
        href: '/api/v2/root_hospital_lab_results/meta/id',
        fieldType: 'STRING',
        name: 'id',
        label: 'id',
        description: 'id of patient with date of sampling',
        attributes: [],
        maxLength: 255,
        auto: false,
        nillable: false,
        readOnly: true,
        labelAttribute: true,
        unique: true,
        visible: true,
        lookupAttribute: true,
        isAggregatable: false
      },
      {
        href: '/api/v2/root_hospital_lab_results/meta/sample_type',
        fieldType: 'CATEGORICAL',
        name: 'sample_type',
        label: 'Sample type',
        attributes: [],
        refEntity: {
          href: '/api/v2/root_hospital_sample_types',
          hrefCollection: '/api/v2/root_hospital_sample_types',
          name: 'root_hospital_sample_types',
          label: 'Sample types',
          description: 'sample types are hospital specific, so placed in the hospital package',
          attributes: [
            {
              href: '/api/v2/root_hospital_sample_types/meta/id',
              fieldType: 'STRING',
              name: 'id',
              label: 'id',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: true,
              labelAttribute: false,
              unique: true,
              visible: true,
              lookupAttribute: false,
              isAggregatable: false
            },
            {
              href: '/api/v2/root_hospital_sample_types/meta/label',
              fieldType: 'STRING',
              name: 'label',
              label: 'label',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: false,
              labelAttribute: true,
              unique: false,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            }
          ],
          labelAttribute: 'label',
          idAttribute: 'id',
          lookupAttributes: [
            'label'
          ],
          isAbstract: false,
          writable: true,
          languageCode: 'en',
          permissions: [
            'READ_METADATA',
            'AGGREGATE_DATA',
            'READ_DATA',
            'ADD_DATA',
            'UPDATE_DATA',
            'UPDATE_METADATA',
            'DELETE_DATA',
            'COUNT_DATA',
            'DELETE_METADATA'
          ]
        },
        auto: false,
        nillable: false,
        readOnly: false,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/root_hospital_lab_results/meta/ESR',
        fieldType: 'DECIMAL',
        name: 'ESR',
        label: 'Erythrocyte sedimentation rate (mm/h)',
        description: 'neonatal(m/f) 0-2.2, <10yrs(m/f) 3-13, <50yrs(f) <20, >50yrs(f) <30, <50(m) <15, >50(m) <20',
        attributes: [],
        auto: false,
        nillable: true,
        readOnly: false,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/root_hospital_lab_results/meta/HB',
        fieldType: 'DECIMAL',
        name: 'HB',
        label: 'Hemoglobine (mM)',
        description: 'normal(f) 7.3-10, anemia(f) <7.3, normal(m) 7/8-10.8, anemia(m) <7.8',
        attributes: [],
        auto: false,
        nillable: true,
        readOnly: false,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/root_hospital_lab_results/meta/hematocrit',
        fieldType: 'DECIMAL',
        name: 'hematocrit',
        label: 'Hematocrit (l/l)',
        description: 'm: 0.45-0.55, f: 0.40-0.50',
        attributes: [],
        auto: false,
        nillable: true,
        readOnly: false,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/root_hospital_lab_results/meta/iron',
        fieldType: 'DECIMAL',
        name: 'iron',
        label: 'Iron (µM)',
        description: 'neonatal(m/f): 17-24, m: 14-28, f: 10-25',
        attributes: [],
        auto: false,
        nillable: true,
        readOnly: false,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/root_hospital_lab_results/meta/PSA',
        fieldType: 'DECIMAL',
        name: 'PSA',
        label: 'Prostate specific antigen (mg/l)',
        description: '<40yrs <2.0, 40-50yrs <2.5, 50-60yrs <3.5, 60-70 <4.5, 70-80 <6.5',
        attributes: [],
        auto: false,
        nillable: true,
        readOnly: false,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/root_hospital_lab_results/meta/proteins',
        fieldType: 'COMPOUND',
        name: 'proteins',
        label: 'Proteins',
        attributes: [
          {
            href: '/api/v2/root_hospital_lab_results/meta/proteins_serum',
            fieldType: 'DECIMAL',
            name: 'proteins_serum',
            label: 'Proteins in serum (g/l)',
            description: 'normal:63-83 g/l',
            attributes: [],
            auto: false,
            nillable: true,
            readOnly: false,
            labelAttribute: false,
            unique: false,
            visible: true,
            lookupAttribute: false,
            isAggregatable: false
          },
          {
            href: '/api/v2/root_hospital_lab_results/meta/proteins_plasma',
            fieldType: 'DECIMAL',
            name: 'proteins_plasma',
            label: 'Proteins in plasma(g/l)',
            description: 'normal:60-80 g/l',
            attributes: [],
            auto: false,
            nillable: true,
            readOnly: false,
            labelAttribute: false,
            unique: false,
            visible: true,
            lookupAttribute: false,
            isAggregatable: false
          }
        ],
        auto: false,
        nillable: true,
        readOnly: false,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/root_hospital_lab_results/meta/thyroid',
        fieldType: 'COMPOUND',
        name: 'thyroid',
        label: 'Thyroid',
        attributes: [
          {
            href: '/api/v2/root_hospital_lab_results/meta/TSH',
            fieldType: 'DECIMAL',
            name: 'TSH',
            label: 'Thyroid specific hormone mU/l',
            description: 'normal: 0.2-3.5',
            attributes: [],
            auto: false,
            nillable: true,
            readOnly: false,
            labelAttribute: false,
            unique: false,
            visible: true,
            lookupAttribute: false,
            isAggregatable: false
          },
          {
            href: '/api/v2/root_hospital_lab_results/meta/FT4',
            fieldType: 'DECIMAL',
            name: 'FT4',
            label: 'Free T4 hormones (pM)',
            description: 'normal: 8-26',
            attributes: [],
            auto: false,
            nillable: true,
            readOnly: false,
            labelAttribute: false,
            unique: false,
            visible: true,
            lookupAttribute: false,
            isAggregatable: false
          }
        ],
        auto: false,
        nillable: true,
        readOnly: false,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/root_hospital_lab_results/meta/cholesterol',
        fieldType: 'DECIMAL',
        name: 'cholesterol',
        label: 'Cholesterol (mM)',
        description: 'normal: < 5.0, lightly increased: 5.0-6.4, increased: 6.5-8.0, highly increased: >8.0',
        attributes: [],
        auto: false,
        nillable: true,
        readOnly: false,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      }
    ],
    labelAttribute: 'id',
    idAttribute: 'id',
    lookupAttributes: [
      'id'
    ],
    isAbstract: false,
    writable: true,
    languageCode: 'en',
    permissions: [
      'READ_METADATA',
      'AGGREGATE_DATA',
      'READ_DATA',
      'ADD_DATA',
      'UPDATE_DATA',
      'UPDATE_METADATA',
      'DELETE_DATA',
      'COUNT_DATA',
      'DELETE_METADATA'
    ]
  },
  start: 0,
  num: 100,
  total: 6,
  items: [
    {
      _href: '/api/v2/root_hospital_lab_results/p000000001_2014_11_11',
      id: 'p000000001_2014_11_11',
      sample_type: {
        _href: '/api/v2/root_hospital_sample_types/blood',
        id: 'blood',
        label: 'Blood'
      },
      ESR: 14,
      HB: 8,
      hematocrit: 0.46,
      iron: 15,
      PSA: 1.6,
      proteins_serum: 74,
      proteins_plasma: 70,
      TSH: 0.3,
      FT4: 10,
      cholesterol: 2.6
    },
    {
      _href: '/api/v2/root_hospital_lab_results/p000000001_2015_01_14',
      id: 'p000000001_2015_01_14',
      sample_type: {
        _href: '/api/v2/root_hospital_sample_types/blood',
        id: 'blood',
        label: 'Blood'
      },
      ESR: 14,
      HB: 9,
      hematocrit: 0.52,
      iron: 20,
      PSA: 1.3,
      proteins_serum: 81,
      proteins_plasma: 72,
      TSH: 2.3,
      FT4: 20,
      cholesterol: 3.5
    },
    {
      _href: '/api/v2/root_hospital_lab_results/p000000002_2015_02_01',
      id: 'p000000002_2015_02_01',
      sample_type: {
        _href: '/api/v2/root_hospital_sample_types/blood',
        id: 'blood',
        label: 'Blood'
      },
      ESR: 15,
      HB: 7.5,
      hematocrit: 0.45,
      iron: 12,
      proteins_serum: 78,
      proteins_plasma: 72,
      TSH: 0.4,
      FT4: 12,
      cholesterol: 3
    },
    {
      _href: '/api/v2/root_hospital_lab_results/p000000003_2004_10_30',
      id: 'p000000003_2004_10_30',
      sample_type: {
        _href: '/api/v2/root_hospital_sample_types/blood',
        id: 'blood',
        label: 'Blood'
      },
      ESR: 17,
      HB: 9,
      hematocrit: 0.47,
      iron: 18,
      PSA: 3.4,
      proteins_serum: 75,
      proteins_plasma: 75,
      TSH: 2.2,
      FT4: 21,
      cholesterol: 4.9
    },
    {
      _href: '/api/v2/root_hospital_lab_results/p000000003_2014_12_19',
      id: 'p000000003_2014_12_19',
      sample_type: {
        _href: '/api/v2/root_hospital_sample_types/blood',
        id: 'blood',
        label: 'Blood'
      },
      ESR: 19,
      HB: 10,
      hematocrit: 0.46,
      iron: 25,
      PSA: 4.2,
      proteins_serum: 74,
      proteins_plasma: 71,
      TSH: 0.9,
      FT4: 24,
      cholesterol: 2.3
    },
    {
      _href: '/api/v2/root_hospital_lab_results/p000000003_2016_09_08',
      id: 'p000000003_2016_09_08',
      sample_type: {
        _href: '/api/v2/root_hospital_sample_types/blood',
        id: 'blood',
        label: 'Blood'
      },
      ESR: 19,
      HB: 9,
      hematocrit: 0.5,
      iron: 16,
      PSA: 4.1,
      proteins_serum: 80,
      proteins_plasma: 74,
      TSH: 1.5,
      FT4: 16,
      cholesterol: 4.5
    }
  ]
}
