module.exports = {
  href: '/api/v2/it_emx_datatypes_TypeTest',
  meta: {
    href: '/api/v2/it_emx_datatypes_TypeTest',
    hrefCollection: '/api/v2/it_emx_datatypes_TypeTest',
    name: 'it_emx_datatypes_TypeTest',
    label: 'TypeTest',
    description: 'MOLGENIS Data types test entity',
    attributes: [
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/id',
        fieldType: 'INT',
        name: 'id',
        label: 'id label',
        attributes: [],
        auto: false,
        nillable: false,
        readOnly: true,
        labelAttribute: true,
        unique: true,
        visible: true,
        lookupAttribute: true,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xbool',
        fieldType: 'BOOL',
        name: 'xbool',
        label: 'xbool',
        description: 'TypeTest boolean attribute',
        attributes: [],
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: 'false',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xboolnillable',
        fieldType: 'BOOL',
        name: 'xboolnillable',
        label: 'xboolnillable label',
        description: 'TypeTest nillable boolean attribute',
        attributes: [],
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: 'true',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xcompound',
        fieldType: 'COMPOUND',
        name: 'xcompound',
        label: 'xcompound label',
        description: 'TypeTest compound attribute',
        attributes: [
          {
            href: '/api/v2/it_emx_datatypes_TypeTest/meta/xcompound_int',
            fieldType: 'INT',
            name: 'xcompound_int',
            label: 'xcompound_int label',
            attributes: [],
            auto: false,
            nillable: true,
            readOnly: false,
            defaultValue: '1',
            labelAttribute: false,
            unique: false,
            visible: true,
            lookupAttribute: false,
            isAggregatable: true
          },
          {
            href: '/api/v2/it_emx_datatypes_TypeTest/meta/xcompound_string',
            fieldType: 'STRING',
            name: 'xcompound_string',
            label: 'xcompound_string label',
            description: 'TypeTest compound string attribute',
            attributes: [],
            maxLength: 255,
            auto: false,
            nillable: true,
            readOnly: false,
            defaultValue: 'xcompound_string',
            labelAttribute: false,
            unique: false,
            visible: true,
            lookupAttribute: false,
            isAggregatable: true
          }
        ],
        auto: false,
        nillable: false,
        readOnly: false,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xcategorical_value',
        fieldType: 'CATEGORICAL',
        name: 'xcategorical_value',
        label: 'xcategorical_value label',
        description: 'TypeTest categorical attribute',
        attributes: [],
        refEntity: {
          href: '/api/v2/it_emx_datatypes_TypeTestRef',
          hrefCollection: '/api/v2/it_emx_datatypes_TypeTestRef',
          name: 'it_emx_datatypes_TypeTestRef',
          label: 'TypeTestRef',
          description: 'MOLGENIS Data types test ref entity',
          attributes: [
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/value',
              fieldType: 'STRING',
              name: 'value',
              label: 'value label',
              description: 'TypeTestRef value attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: true,
              labelAttribute: false,
              unique: true,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            },
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/label',
              fieldType: 'STRING',
              name: 'label',
              label: 'label label',
              description: 'TypeTestRef label attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: false,
              labelAttribute: true,
              unique: false,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            }
          ],
          labelAttribute: 'label',
          idAttribute: 'value',
          lookupAttributes: [
            'value',
            'label'
          ],
          isAbstract: false,
          writable: false,
          languageCode: 'en',
          permissions: [
            'READ_METADATA',
            'COUNT_DATA',
            'AGGREGATE_DATA',
            'READ_DATA'
          ]
        },
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: 'ref1',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xcategoricalnillable_value',
        fieldType: 'CATEGORICAL',
        name: 'xcategoricalnillable_value',
        label: 'xcategoricalnillable_value',
        description: 'TypeTest nillable categorical attribute',
        attributes: [],
        refEntity: {
          href: '/api/v2/it_emx_datatypes_TypeTestRef',
          hrefCollection: '/api/v2/it_emx_datatypes_TypeTestRef',
          name: 'it_emx_datatypes_TypeTestRef',
          label: 'TypeTestRef',
          description: 'MOLGENIS Data types test ref entity',
          attributes: [
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/value',
              fieldType: 'STRING',
              name: 'value',
              label: 'value label',
              description: 'TypeTestRef value attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: true,
              labelAttribute: false,
              unique: true,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            },
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/label',
              fieldType: 'STRING',
              name: 'label',
              label: 'label label',
              description: 'TypeTestRef label attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: false,
              labelAttribute: true,
              unique: false,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            }
          ],
          labelAttribute: 'label',
          idAttribute: 'value',
          lookupAttributes: [
            'value',
            'label'
          ],
          isAbstract: false,
          writable: false,
          languageCode: 'en',
          permissions: [
            'READ_METADATA',
            'COUNT_DATA',
            'AGGREGATE_DATA',
            'READ_DATA'
          ]
        },
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: 'ref2',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xcategoricalmref_value',
        fieldType: 'CATEGORICAL_MREF',
        name: 'xcategoricalmref_value',
        label: 'xcategoricalmref_value',
        description: 'TypeTest categorical mref attribute',
        attributes: [],
        refEntity: {
          href: '/api/v2/it_emx_datatypes_TypeTestRef',
          hrefCollection: '/api/v2/it_emx_datatypes_TypeTestRef',
          name: 'it_emx_datatypes_TypeTestRef',
          label: 'TypeTestRef',
          description: 'MOLGENIS Data types test ref entity',
          attributes: [
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/value',
              fieldType: 'STRING',
              name: 'value',
              label: 'value label',
              description: 'TypeTestRef value attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: true,
              labelAttribute: false,
              unique: true,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            },
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/label',
              fieldType: 'STRING',
              name: 'label',
              label: 'label label',
              description: 'TypeTestRef label attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: false,
              labelAttribute: true,
              unique: false,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            }
          ],
          labelAttribute: 'label',
          idAttribute: 'value',
          lookupAttributes: [
            'value',
            'label'
          ],
          isAbstract: false,
          writable: false,
          languageCode: 'en',
          permissions: [
            'READ_METADATA',
            'COUNT_DATA',
            'AGGREGATE_DATA',
            'READ_DATA'
          ]
        },
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: 'ref1,ref2',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xcatmrefnillable_value',
        fieldType: 'CATEGORICAL_MREF',
        name: 'xcatmrefnillable_value',
        label: 'xcatmrefnillable_value',
        description: 'TypeTest nillable categorical mref attribute',
        attributes: [],
        refEntity: {
          href: '/api/v2/it_emx_datatypes_TypeTestRef',
          hrefCollection: '/api/v2/it_emx_datatypes_TypeTestRef',
          name: 'it_emx_datatypes_TypeTestRef',
          label: 'TypeTestRef',
          description: 'MOLGENIS Data types test ref entity',
          attributes: [
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/value',
              fieldType: 'STRING',
              name: 'value',
              label: 'value label',
              description: 'TypeTestRef value attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: true,
              labelAttribute: false,
              unique: true,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            },
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/label',
              fieldType: 'STRING',
              name: 'label',
              label: 'label label',
              description: 'TypeTestRef label attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: false,
              labelAttribute: true,
              unique: false,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            }
          ],
          labelAttribute: 'label',
          idAttribute: 'value',
          lookupAttributes: [
            'value',
            'label'
          ],
          isAbstract: false,
          writable: false,
          languageCode: 'en',
          permissions: [
            'READ_METADATA',
            'COUNT_DATA',
            'AGGREGATE_DATA',
            'READ_DATA'
          ]
        },
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: 'ref1,ref3',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xdate',
        fieldType: 'DATE',
        name: 'xdate',
        label: 'xdate label',
        description: 'Typetest date attribute',
        attributes: [],
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: '2014-08-01T00:00',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xdatenillable',
        fieldType: 'DATE',
        name: 'xdatenillable',
        label: 'xdatenillable label',
        description: 'Typetest nillable date attribute',
        attributes: [],
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: '2015-04-01T00:00',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xdatetime',
        fieldType: 'DATE_TIME',
        name: 'xdatetime',
        label: 'xdatetime label',
        attributes: [],
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: '1985-08-12T11:12:13+0500',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xdatetimenillable',
        fieldType: 'DATE_TIME',
        name: 'xdatetimenillable',
        label: 'xdatetimenillable label',
        description: 'Typetest nillable datetime attribute',
        attributes: [],
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: '1985-08-12T11:12:13+0500',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xdecimal',
        fieldType: 'DECIMAL',
        name: 'xdecimal',
        label: 'xdecimal label',
        description: 'Typetest decimal attribute',
        attributes: [],
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: '10.234',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xdecimalnillable',
        fieldType: 'DECIMAL',
        name: 'xdecimalnillable',
        label: 'xdecimalnillable label',
        description: 'Typetest nillable decimal attribute',
        attributes: [],
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: '15.666',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xemail',
        fieldType: 'EMAIL',
        name: 'xemail',
        label: 'xemail label',
        description: 'Typetest email attribute',
        attributes: [],
        maxLength: 255,
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: 'test@x.y.z',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xemailnillable',
        fieldType: 'EMAIL',
        name: 'xemailnillable',
        label: 'xemailnillable label',
        description: 'Typetest nillable email attribute',
        attributes: [],
        maxLength: 255,
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: 'molgenis@gmail.com',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xenum',
        fieldType: 'ENUM',
        name: 'xenum',
        label: 'xenum',
        description: 'Typetest enum attribute',
        attributes: [],
        enumOptions: [
          'enum1',
          'enum2',
          'enum3'
        ],
        maxLength: 255,
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: 'enum1',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xenumnillable',
        fieldType: 'ENUM',
        name: 'xenumnillable',
        label: 'xenumnillable label',
        description: 'Typetest nillable enum attribute',
        attributes: [],
        enumOptions: [
          'enum1',
          'enum2',
          'enum3'
        ],
        maxLength: 255,
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: 'enum3',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xhtml',
        fieldType: 'HTML',
        name: 'xhtml',
        label: 'xhtml label',
        attributes: [],
        maxLength: 65535,
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: '<h1>html</h1>',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xhtmlnillable',
        fieldType: 'HTML',
        name: 'xhtmlnillable',
        label: 'xhtmlnillable label',
        description: 'Typetest nillable html attribute',
        attributes: [],
        maxLength: 65535,
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: '<h1>html 2</h1>',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xhyperlink',
        fieldType: 'HYPERLINK',
        name: 'xhyperlink',
        label: 'xhyperlink label',
        description: 'Typetest hyperlink attribute',
        attributes: [],
        maxLength: 255,
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: 'http://www.nu.nl/',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xhyperlinknillable',
        fieldType: 'HYPERLINK',
        name: 'xhyperlinknillable',
        label: 'xhyperlinknillable label',
        description: 'Typetest nillable hyperlink attribute',
        attributes: [],
        maxLength: 255,
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: 'http://www.github.com/',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xint',
        fieldType: 'INT',
        name: 'xint',
        label: 'xint label',
        description: 'Typetest int attribute',
        attributes: [],
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: '3',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xintnillable',
        fieldType: 'INT',
        name: 'xintnillable',
        label: 'xintnillable label',
        attributes: [],
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: '1',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xintrange',
        fieldType: 'INT',
        name: 'xintrange',
        label: 'xintrange label',
        description: 'Typetest int range attribute',
        attributes: [],
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: '6',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false,
        range: {
          max: 10
        }
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xintrangenillable',
        fieldType: 'INT',
        name: 'xintrangenillable',
        label: 'xintrangenillable label',
        description: 'Typetest nillable intrange attribute',
        attributes: [],
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: '77',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false,
        range: {
          min: 0
        }
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xlong',
        fieldType: 'LONG',
        name: 'xlong',
        label: 'xlong label',
        description: 'Typetest long attribute',
        attributes: [],
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: '12342151234',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xlongnillable',
        fieldType: 'LONG',
        name: 'xlongnillable',
        label: 'xlongnillable label',
        attributes: [],
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: '12342151234',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xlongrange',
        fieldType: 'LONG',
        name: 'xlongrange',
        label: 'xlongrange label',
        description: 'Typetest longrange attribute',
        attributes: [],
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: '5',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true,
        range: {
          min: 0,
          max: 10
        }
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xlongrangenillable',
        fieldType: 'LONG',
        name: 'xlongrangenillable',
        label: 'xlongrangenillable label',
        description: 'Typetest nillable longrange attribute',
        attributes: [],
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: '3',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true,
        range: {
          min: 0,
          max: 10
        }
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xmref_value',
        fieldType: 'MREF',
        name: 'xmref_value',
        label: 'xmref_value',
        description: 'Typetest mref attribute',
        attributes: [],
        refEntity: {
          href: '/api/v2/it_emx_datatypes_TypeTestRef',
          hrefCollection: '/api/v2/it_emx_datatypes_TypeTestRef',
          name: 'it_emx_datatypes_TypeTestRef',
          label: 'TypeTestRef',
          description: 'MOLGENIS Data types test ref entity',
          attributes: [
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/value',
              fieldType: 'STRING',
              name: 'value',
              label: 'value label',
              description: 'TypeTestRef value attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: true,
              labelAttribute: false,
              unique: true,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            },
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/label',
              fieldType: 'STRING',
              name: 'label',
              label: 'label label',
              description: 'TypeTestRef label attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: false,
              labelAttribute: true,
              unique: false,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            }
          ],
          labelAttribute: 'label',
          idAttribute: 'value',
          lookupAttributes: [
            'value',
            'label'
          ],
          isAbstract: false,
          writable: false,
          languageCode: 'en',
          permissions: [
            'READ_METADATA',
            'COUNT_DATA',
            'AGGREGATE_DATA',
            'READ_DATA'
          ]
        },
        auto: false,
        nillable: false,
        readOnly: false,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xmrefnillable_value',
        fieldType: 'MREF',
        name: 'xmrefnillable_value',
        label: 'xmrefnillable_value',
        attributes: [],
        refEntity: {
          href: '/api/v2/it_emx_datatypes_TypeTestRef',
          hrefCollection: '/api/v2/it_emx_datatypes_TypeTestRef',
          name: 'it_emx_datatypes_TypeTestRef',
          label: 'TypeTestRef',
          description: 'MOLGENIS Data types test ref entity',
          attributes: [
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/value',
              fieldType: 'STRING',
              name: 'value',
              label: 'value label',
              description: 'TypeTestRef value attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: true,
              labelAttribute: false,
              unique: true,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            },
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/label',
              fieldType: 'STRING',
              name: 'label',
              label: 'label label',
              description: 'TypeTestRef label attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: false,
              labelAttribute: true,
              unique: false,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            }
          ],
          labelAttribute: 'label',
          idAttribute: 'value',
          lookupAttributes: [
            'value',
            'label'
          ],
          isAbstract: false,
          writable: false,
          languageCode: 'en',
          permissions: [
            'READ_METADATA',
            'COUNT_DATA',
            'AGGREGATE_DATA',
            'READ_DATA'
          ]
        },
        auto: false,
        nillable: true,
        readOnly: false,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xstring',
        fieldType: 'STRING',
        name: 'xstring',
        label: 'xstring label',
        description: 'Typetest string attribute',
        attributes: [],
        maxLength: 255,
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: 'xstring',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xstringnillable',
        fieldType: 'STRING',
        name: 'xstringnillable',
        label: 'xstringnillable label',
        description: 'Typetest nillable string attribute',
        attributes: [],
        maxLength: 255,
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: 'xstringnillable',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xtext',
        fieldType: 'TEXT',
        name: 'xtext',
        label: 'xtext label',
        attributes: [],
        maxLength: 65535,
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: 'xtext',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xtextnillable',
        fieldType: 'TEXT',
        name: 'xtextnillable',
        label: 'xtextnillable label',
        description: 'Typetest nillable text attribute',
        attributes: [],
        maxLength: 65535,
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: 'xtextnillable',
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xxref_value',
        fieldType: 'XREF',
        name: 'xxref_value',
        label: 'xxref_value',
        description: 'Typetest xref attribute',
        attributes: [],
        refEntity: {
          href: '/api/v2/it_emx_datatypes_TypeTestRef',
          hrefCollection: '/api/v2/it_emx_datatypes_TypeTestRef',
          name: 'it_emx_datatypes_TypeTestRef',
          label: 'TypeTestRef',
          description: 'MOLGENIS Data types test ref entity',
          attributes: [
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/value',
              fieldType: 'STRING',
              name: 'value',
              label: 'value label',
              description: 'TypeTestRef value attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: true,
              labelAttribute: false,
              unique: true,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            },
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/label',
              fieldType: 'STRING',
              name: 'label',
              label: 'label label',
              description: 'TypeTestRef label attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: false,
              labelAttribute: true,
              unique: false,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            }
          ],
          labelAttribute: 'label',
          idAttribute: 'value',
          lookupAttributes: [
            'value',
            'label'
          ],
          isAbstract: false,
          writable: false,
          languageCode: 'en',
          permissions: [
            'READ_METADATA',
            'COUNT_DATA',
            'AGGREGATE_DATA',
            'READ_DATA'
          ]
        },
        auto: false,
        nillable: false,
        readOnly: false,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: true
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xxrefnillable_value',
        fieldType: 'XREF',
        name: 'xxrefnillable_value',
        label: 'xxrefnillable_value',
        description: 'Typetest nillable xref attribute_value',
        attributes: [],
        refEntity: {
          href: '/api/v2/it_emx_datatypes_TypeTestRef',
          hrefCollection: '/api/v2/it_emx_datatypes_TypeTestRef',
          name: 'it_emx_datatypes_TypeTestRef',
          label: 'TypeTestRef',
          description: 'MOLGENIS Data types test ref entity',
          attributes: [
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/value',
              fieldType: 'STRING',
              name: 'value',
              label: 'value label',
              description: 'TypeTestRef value attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: true,
              labelAttribute: false,
              unique: true,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            },
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/label',
              fieldType: 'STRING',
              name: 'label',
              label: 'label label',
              description: 'TypeTestRef label attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: false,
              labelAttribute: true,
              unique: false,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            }
          ],
          labelAttribute: 'label',
          idAttribute: 'value',
          lookupAttributes: [
            'value',
            'label'
          ],
          isAbstract: false,
          writable: false,
          languageCode: 'en',
          permissions: [
            'READ_METADATA',
            'COUNT_DATA',
            'AGGREGATE_DATA',
            'READ_DATA'
          ]
        },
        auto: false,
        nillable: true,
        readOnly: false,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xstring_hidden',
        fieldType: 'STRING',
        name: 'xstring_hidden',
        label: 'xstring_hidden label',
        description: 'Typetest hidden string attribute',
        attributes: [],
        maxLength: 255,
        auto: false,
        nillable: false,
        readOnly: false,
        defaultValue: 'xstring',
        labelAttribute: false,
        unique: false,
        visible: false,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xstringnillable_hidden',
        fieldType: 'STRING',
        name: 'xstringnillable_hidden',
        label: 'xstringnillable_hidden label',
        description: 'Typetest nillable hidden string attribute',
        attributes: [],
        maxLength: 255,
        auto: false,
        nillable: true,
        readOnly: false,
        defaultValue: 'xstringhidden',
        labelAttribute: false,
        unique: false,
        visible: false,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xstring_unique',
        fieldType: 'STRING',
        name: 'xstring_unique',
        label: 'xstring_unique label',
        attributes: [],
        maxLength: 255,
        auto: false,
        nillable: false,
        readOnly: false,
        labelAttribute: false,
        unique: true,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xint_unique',
        fieldType: 'INT',
        name: 'xint_unique',
        label: 'xint_unique label',
        description: 'Typetest unique int attribute',
        attributes: [],
        auto: false,
        nillable: false,
        readOnly: false,
        labelAttribute: false,
        unique: true,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xxref_unique',
        fieldType: 'XREF',
        name: 'xxref_unique',
        label: 'xxref_unique',
        description: 'Typetest unique xref attribute',
        attributes: [],
        refEntity: {
          href: '/api/v2/it_emx_datatypes_TypeTestRef',
          hrefCollection: '/api/v2/it_emx_datatypes_TypeTestRef',
          name: 'it_emx_datatypes_TypeTestRef',
          label: 'TypeTestRef',
          description: 'MOLGENIS Data types test ref entity',
          attributes: [
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/value',
              fieldType: 'STRING',
              name: 'value',
              label: 'value label',
              description: 'TypeTestRef value attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: true,
              labelAttribute: false,
              unique: true,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            },
            {
              href: '/api/v2/it_emx_datatypes_TypeTestRef/meta/label',
              fieldType: 'STRING',
              name: 'label',
              label: 'label label',
              description: 'TypeTestRef label attribute',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: false,
              labelAttribute: true,
              unique: false,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            }
          ],
          labelAttribute: 'label',
          idAttribute: 'value',
          lookupAttributes: [
            'value',
            'label'
          ],
          isAbstract: false,
          writable: false,
          languageCode: 'en',
          permissions: [
            'READ_METADATA',
            'COUNT_DATA',
            'AGGREGATE_DATA',
            'READ_DATA'
          ]
        },
        auto: false,
        nillable: true,
        readOnly: false,
        labelAttribute: false,
        unique: true,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xfile',
        fieldType: 'FILE',
        name: 'xfile',
        label: 'xfile',
        attributes: [],
        refEntity: {
          href: '/api/v2/sys_FileMeta',
          hrefCollection: '/api/v2/sys_FileMeta',
          name: 'sys_FileMeta',
          label: 'File metadata',
          attributes: [
            {
              href: '/api/v2/sys_FileMeta/meta/id',
              fieldType: 'STRING',
              name: 'id',
              label: 'Id',
              attributes: [],
              maxLength: 255,
              auto: true,
              nillable: false,
              readOnly: true,
              labelAttribute: false,
              unique: true,
              visible: false,
              lookupAttribute: false,
              isAggregatable: false
            },
            {
              href: '/api/v2/sys_FileMeta/meta/filename',
              fieldType: 'STRING',
              name: 'filename',
              label: 'Filename',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: false,
              labelAttribute: true,
              unique: false,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            },
            {
              href: '/api/v2/sys_FileMeta/meta/url',
              fieldType: 'HYPERLINK',
              name: 'url',
              label: 'URL',
              description: 'File download URL',
              attributes: [],
              maxLength: 255,
              auto: false,
              nillable: false,
              readOnly: false,
              labelAttribute: false,
              unique: true,
              visible: true,
              lookupAttribute: false,
              isAggregatable: false
            }
          ],
          labelAttribute: 'filename',
          idAttribute: 'id',
          lookupAttributes: [
            'filename',
            'contentType'
          ],
          isAbstract: false,
          writable: false,
          languageCode: 'en',
          permissions: [
            'READ_METADATA',
            'COUNT_DATA',
            'AGGREGATE_DATA',
            'READ_DATA'
          ]
        },
        auto: false,
        nillable: true,
        readOnly: false,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xcomputedxref',
        fieldType: 'XREF',
        name: 'xcomputedxref',
        label: 'xcomputedxref label',
        description: 'Typetest computed xref attribute',
        attributes: [],
        refEntity: {
          href: '/api/v2/it_emx_datatypes_Location',
          hrefCollection: '/api/v2/it_emx_datatypes_Location',
          name: 'it_emx_datatypes_Location',
          label: 'Location',
          description: 'MOLGENIS Data types test location',
          attributes: [
            {
              href: '/api/v2/it_emx_datatypes_Location/meta/Position',
              fieldType: 'INT',
              name: 'Position',
              label: 'Position label',
              description: 'Location Position attribute',
              attributes: [],
              auto: false,
              nillable: false,
              readOnly: true,
              labelAttribute: true,
              unique: true,
              visible: true,
              lookupAttribute: true,
              isAggregatable: false
            }
          ],
          labelAttribute: 'Position',
          idAttribute: 'Position',
          lookupAttributes: [
            'Position'
          ],
          isAbstract: false,
          writable: false,
          languageCode: 'en',
          permissions: [
            'READ_METADATA',
            'COUNT_DATA',
            'AGGREGATE_DATA',
            'READ_DATA'
          ]
        },
        auto: false,
        nillable: true,
        readOnly: true,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false,
        expression: '{Chromosome: xstring, Position: xint}'
      },
      {
        href: '/api/v2/it_emx_datatypes_TypeTest/meta/xcomputedint',
        fieldType: 'INT',
        name: 'xcomputedint',
        label: 'xcomputedint label',
        description: 'Typetest computed int attribute',
        attributes: [],
        auto: false,
        nillable: true,
        readOnly: true,
        labelAttribute: false,
        unique: false,
        visible: true,
        lookupAttribute: false,
        isAggregatable: false,
        expression: 'xint'
      }
    ],
    labelAttribute: 'id',
    idAttribute: 'id',
    lookupAttributes: [
      'id'
    ],
    isAbstract: false,
    writable: false,
    languageCode: 'en',
    permissions: [
      'READ_METADATA',
      'COUNT_DATA',
      'AGGREGATE_DATA',
      'READ_DATA'
    ]
  },
  start: 0,
  num: 0,
  total: 38,
  nextHref: 'http://data-v3.dev.molgenis.org:443/api/v2/it_emx_datatypes_TypeTest?num=0&start=0',
  items: []
}
