// tslint:disable
/**
 * MOLGENIS data & metadata API
 * RESTful API to create/read/update/delete data and metadata.
 *
 * The version of the OpenAPI document: 3.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Links
 */
export interface Links {
    /**
     *
     * @type {string}
     * @memberof Links
     */
    previous?: string;
    /**
     *
     * @type {string}
     * @memberof Links
     */
    self: string;
    /**
     *
     * @type {string}
     * @memberof Links
     */
    next?: string;
}
